<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ID_manager_id</name>
   <tag></tag>
   <elementGuidId>200eff10-e8d1-43a4-90c5-b78962ee5d69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.input-wrap > div.input-box > input[name=&quot;manager_id&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='manager_id'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>626e65e3-d376-402f-a327-d01449bf150e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>manager_id</value>
      <webElementGuid>7cde2e53-a624-411e-9167-513aecaf398c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9548d49a-09fe-4f1f-914c-3b23d28ce103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c882cce-fc7c-475e-b11b-0bed9043728f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;wrap&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;content scrollBar&quot;]/div[@class=&quot;cont&quot;]/form[1]/div[1]/div[@class=&quot;modal-wrap&quot;]/div[@class=&quot;modal&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;modal-inner&quot;]/div[@class=&quot;input-wrap&quot;]/div[@class=&quot;input-box&quot;]/input[@class=&quot;input&quot;]</value>
      <webElementGuid>2585722a-9eb6-4657-b8c9-fa49c326b469</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='manager_id'])[2]</value>
      <webElementGuid>ba00d50d-af8b-4ef6-b6eb-f0113707e800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div/form/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>d5aff4db-be89-4a07-8c69-ae508ae3c8cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>873a30f9-5a2f-4a22-8998-9eaec2fa82f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'manager_id' and @type = 'text']</value>
      <webElementGuid>900456e5-fc8f-40ad-a9c1-f3e0f1fd808c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
