<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__manager_name</name>
   <tag></tag>
   <elementGuidId>a90fe240-1406-4d9a-be7b-46b8ce30dcc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.input-wrap > div.input-box > input[name=&quot;manager_name&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='manager_name'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f05a1ea-b684-47ed-8b84-2526a3b65407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>manager_name</value>
      <webElementGuid>8355d548-a62c-4ba2-b609-acf53b683619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fcbf6268-c20e-4734-91f6-56c06fd11ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8bd98158-b448-485f-8094-6cb3568db652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;wrap&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;content scrollBar&quot;]/div[@class=&quot;cont&quot;]/form[1]/div[1]/div[@class=&quot;modal-wrap&quot;]/div[@class=&quot;modal&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;modal-inner&quot;]/div[@class=&quot;input-wrap&quot;]/div[@class=&quot;input-box&quot;]/input[@class=&quot;input&quot;]</value>
      <webElementGuid>f869d974-70d8-492b-a932-5213eba9ba7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='manager_name'])[2]</value>
      <webElementGuid>2bbee214-22af-4167-ad2b-18f6ed967e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div/form/div/div/div/div[2]/div/div[4]/div/input</value>
      <webElementGuid>91a9ef3c-97c1-4cc9-9674-2c7244eaf5a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>4d4b8265-8c87-4673-b8c6-b8dc1476eb3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'manager_name' and @type = 'text']</value>
      <webElementGuid>ac40c21e-1b1d-4819-837a-08bbdf7022c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
