<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_, )  166,  ,  532_region_name</name>
   <tag></tag>
   <elementGuidId>3e51de61-ccd2-4b96-821b-261bde7e1c37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='region_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#region_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd428d3b-2a0a-4c5d-ba4a-6bccd271ed7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c380d813-16ee-4226-b95b-27ae1a8caf8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>region_name</value>
      <webElementGuid>c45d18e2-b0ad-4f4b-88b5-81befc3d432e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>주소 검색</value>
      <webElementGuid>ba57f0d8-2be1-48cb-888a-9cf137b73277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tf_keyword</value>
      <webElementGuid>46057ee5-de5f-4011-90ae-0d196c1bcbba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>region_name</value>
      <webElementGuid>1f42be15-faad-4fcd-acc3-37cb93b94af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6d8f916d-659a-4a32-a578-f6194656b36f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clearable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>41c051e6-3ede-4b11-bae8-65ff8da923ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;region_name&quot;)</value>
      <webElementGuid>578cba7e-8d06-450b-a078-736aa07c3694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/join3/Page_Daum Postcode Service/iframe_concat(id(, , __kakao__viewerFrame_1_320936</value>
      <webElementGuid>54388f35-8f82-4ee9-8779-d349a87bdc04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='region_name']</value>
      <webElementGuid>ef8e937a-2612-4cfe-b3ff-7c2e9242544b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/fieldset/div/div/input</value>
      <webElementGuid>333442ba-f31a-488d-9442-35ec8e092cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>68c51bab-3bc9-404d-8f78-bf484e90f13e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'region_name' and @title = '주소 검색' and @name = 'region_name']</value>
      <webElementGuid>ccefe2cb-6e59-47b8-a5e2-0f02c960227a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
