<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_, )  166,  ,  532_region_name (1)</name>
   <tag></tag>
   <elementGuidId>c54fa1fa-fb49-4a01-a2ea-bfbd5db8a084</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='region_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#region_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>690e5715-d3b0-4670-a3ae-8416ffe26f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8085fe05-959e-4141-830b-49f2fdbf53f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>region_name</value>
      <webElementGuid>eb8d41a2-4e7b-4cf6-9c9f-271f7cc7b4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>주소 검색</value>
      <webElementGuid>d6b3457b-7bba-448b-9ab7-829fba4fdd9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tf_keyword</value>
      <webElementGuid>b72f467c-503b-461c-8c82-a279e2e42f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>region_name</value>
      <webElementGuid>677faa26-c4b7-4802-ae5a-689a646e2c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>992517fe-2220-444c-8230-2ba2b38e07c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clearable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>62c04f0a-1012-40c9-beba-602371c1420c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;region_name&quot;)</value>
      <webElementGuid>a70e4d1c-4e9d-45d4-b9da-ad21cba2f0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/join3/Page_Daum Postcode Service/iframe___kakao__viewerFrame_1</value>
      <webElementGuid>c5f05908-eb1e-4215-985f-688b702eab41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='region_name']</value>
      <webElementGuid>cedbfc74-18a8-4f8d-b29f-87f5cb144665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/fieldset/div/div/input</value>
      <webElementGuid>876666bd-a7ff-400a-ad13-e7a99caad03f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>399bb379-3423-4efa-9848-d4fab49c0321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'region_name' and @title = '주소 검색' and @name = 'region_name']</value>
      <webElementGuid>386685fe-bf00-484b-94cf-ecd11daae68b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
