<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>b2a7377d-dea3-4195-a980-4e5cccd53139</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='searchForm']/fieldset/div/button[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn_search > span.img_post</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3587123c-d221-4cc5-93b8-c548bd2d5e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img_post</value>
      <webElementGuid>fb48841b-b0c5-4194-8f15-788996c4a5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>검색</value>
      <webElementGuid>0d30d35c-20b4-4b57-824e-dea18382a613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchForm&quot;)/fieldset[@class=&quot;fld_inside&quot;]/div[@class=&quot;post_search&quot;]/button[@class=&quot;btn_search&quot;]/span[@class=&quot;img_post&quot;]</value>
      <webElementGuid>a54f25ec-4f1d-47b8-95c5-6d09578a3052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/join3/Page_Daum Postcode Service/iframe___kakao__viewerFrame_1</value>
      <webElementGuid>a7235e91-3457-4310-819c-96854df5906d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/fieldset/div/button[2]/span</value>
      <webElementGuid>1524dd48-dc6f-4121-a548-46d5f02028d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='취소'])[1]/following::span[1]</value>
      <webElementGuid>0ae2c4aa-7606-4373-a6a1-c163335f88a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='검색할 도로명/지번주소를 입력, 예시) 판교역로 166, 분당 주공, 백현동 532'])[1]/following::span[2]</value>
      <webElementGuid>e62946a1-caf7-4423-b86f-7b51c8bb3d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='예) 판교역로 166, 분당 주공, 백현동 532'])[1]/preceding::span[1]</value>
      <webElementGuid>a77aa2e0-ef15-4964-a51d-ec07fe8f21b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='부산광역시 해운대구 APEC로'])[1]/preceding::span[2]</value>
      <webElementGuid>494ea92d-1f7c-4c73-a83a-cdf4d9e823de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='검색']/parent::*</value>
      <webElementGuid>fc59bf53-25c1-414c-a5a9-2ca01d948da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>c4154828-97e4-4ab9-afd5-16344f34c802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '검색' or . = '검색')]</value>
      <webElementGuid>a6f48c9a-6b1b-4166-92c4-664d837a19e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
