<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ID_adminId</name>
   <tag></tag>
   <elementGuidId>e6963db8-c4ab-4603-b54f-e985971725a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#adminId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='adminId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc472f1d-db3a-48b4-8473-43c3dc87c104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f027e792-3df2-4326-8884-b37405521575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>adminId</value>
      <webElementGuid>72b208d0-e21a-4b3d-8b73-b31a59a323c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>아이디 입력</value>
      <webElementGuid>ea19c0e9-9cd5-464f-9261-1d5c86fe4627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adminId&quot;)</value>
      <webElementGuid>9a70ff66-89eb-40cd-a51e-d8cea718e287</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='adminId']</value>
      <webElementGuid>68edac9f-60b2-4303-9152-3a472747aba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='adminForm']/div/div/input</value>
      <webElementGuid>a3720449-c1fa-44ef-8907-64b52f2ec61d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4c7ff8a0-2af1-4fe0-9af4-c323be2b0ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'adminId' and @placeholder = '아이디 입력']</value>
      <webElementGuid>92be924e-ead5-44bb-ba4e-5e64f679e67d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
