<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__adminName</name>
   <tag></tag>
   <elementGuidId>e6656085-faf5-4f5f-8de4-753d66f39067</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#adminName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='adminName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca15de96-33da-4279-87a9-84b9cdbeaa64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>87dd891e-2b61-476f-a27f-bc7f8e7e0b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>adminName</value>
      <webElementGuid>ecd86800-5ca7-47af-8029-650410e02dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>실명 입력</value>
      <webElementGuid>500047bf-852a-482f-94e4-ad390864d245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adminName&quot;)</value>
      <webElementGuid>17259b6b-6e50-4bac-8e0d-a3bb24e549d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='adminName']</value>
      <webElementGuid>2e529506-1338-4c57-9bad-f31a11f5d9e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='adminForm']/div[4]/input</value>
      <webElementGuid>7a9ada1d-aa80-4817-a42c-7ee8d6e18b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>a71fb821-34da-489a-968f-cf80f903a88d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'adminName' and @placeholder = '실명 입력']</value>
      <webElementGuid>8baa15a0-c2c2-4f01-883e-0af7b30712f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
