<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SMS_marketing</name>
   <tag></tag>
   <elementGuidId>522515ac-2843-48e8-802d-47607bf95bd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;marketing&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='marketing']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a97a4f2d-3fe7-48ef-992d-45de86f17010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>14e99683-2b37-4d04-84e4-9c291da01214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>marketing</value>
      <webElementGuid>3d1eb60b-1a7d-4f19-91fc-39ef26019885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>sms</value>
      <webElementGuid>deb0da0e-b910-404d-a171-596df8864a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adminForm&quot;)/div[@class=&quot;field&quot;]/div[@class=&quot;radio-group&quot;]/label[@class=&quot;radio-item&quot;]/input[1]</value>
      <webElementGuid>174433a9-2972-4818-b0d7-28f3fccb7585</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='marketing']</value>
      <webElementGuid>856a946e-1066-424c-8ab1-73d3a5fecc19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='adminForm']/div[7]/div/label/input</value>
      <webElementGuid>8e8d3845-965f-47e6-8874-4fe64360c90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>0259777c-dfd8-40dc-88b0-38c71e5a6fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'marketing']</value>
      <webElementGuid>f64a0891-7cfa-4a9c-bea6-929e053c09fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
