<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__adminName</name>
   <tag></tag>
   <elementGuidId>5f405998-bfe1-41f7-930d-f79a400b6887</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#adminName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='adminName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a14ac968-0e62-4dfa-b144-4fde807ba983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e9904b4-5ee8-452d-9494-da6da586935c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>adminName</value>
      <webElementGuid>c327dbc4-6f99-498f-ba76-41227d4f28c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>실명 입력</value>
      <webElementGuid>5a7d0aa4-b533-4121-908a-8ffa04975d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adminName&quot;)</value>
      <webElementGuid>9bcb03dc-f64b-459f-b836-facbd07c9065</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='adminName']</value>
      <webElementGuid>1b3ffe4c-e255-460f-9f7d-c5da1a55549a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='adminForm']/div[4]/input</value>
      <webElementGuid>8cb054c7-eed1-4f6c-85e7-a827526e19ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>34b4e106-9406-40f9-8f18-4c0001a2dcdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'adminName' and @placeholder = '실명 입력']</value>
      <webElementGuid>eb670d03-54f5-462a-941c-70d56910c1d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
