<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ID_adminId</name>
   <tag></tag>
   <elementGuidId>142d76fa-78a5-4110-b874-4ca735bd3d72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#adminId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='adminId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>456813a3-4e7a-4afa-8292-f11b7a5798c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a31712c4-5eb8-4a4e-b589-7177c2401188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>adminId</value>
      <webElementGuid>63988302-8ec8-4be3-bd82-2e424c2dd28e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>아이디 입력 (이모지 ✨)</value>
      <webElementGuid>146e72c9-a651-4b21-bb43-4495e05e84bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>6759d6c7-99da-4dec-9f73-78087f318521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adminId&quot;)</value>
      <webElementGuid>e5197f46-ccfb-40af-847a-6be0c8ea8311</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='adminId']</value>
      <webElementGuid>dc9f70d1-867d-4bce-b7d6-60e7dc4bdb27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='adminForm']/div/div/input</value>
      <webElementGuid>006c58dd-6e69-47b0-9ec9-1ae3e29d548e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6e7ddfab-f2f9-42bf-afc5-ee650397b0f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'adminId' and @placeholder = '아이디 입력 (이모지 ✨)']</value>
      <webElementGuid>ed70c1d0-d705-453b-9130-715c85300c12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
