<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__adminEmail</name>
   <tag></tag>
   <elementGuidId>b487c602-ddb2-4142-9390-cfce5f66d91c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#adminEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='adminEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8373ca64-44fb-4862-9a60-463cc8a41933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>66154774-31e1-41b0-b2a9-8eba49984b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>adminEmail</value>
      <webElementGuid>f64525dd-4775-41ba-9c6e-1bb90a752d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>example@domain.com</value>
      <webElementGuid>97fac9b5-98cf-43c0-967a-bbf88ca1b430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adminEmail&quot;)</value>
      <webElementGuid>e633e93c-31a2-499c-a0b5-d08ca3a4bd3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='adminEmail']</value>
      <webElementGuid>8644027f-24d9-4f89-8f2d-277ea6b4ee1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='adminForm']/div[5]/input</value>
      <webElementGuid>2c0fd95f-e590-4eca-926a-154c89c90e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>ac2bb1ba-6cec-4b53-b48f-9d053772754b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'adminEmail' and @placeholder = 'example@domain.com']</value>
      <webElementGuid>9cc3bf80-85ef-4a1c-97fb-796bd165c423</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
