<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ID ( )_adminId</name>
   <tag></tag>
   <elementGuidId>2ad1cd89-6969-4cc7-831e-8fe8c5b8ee00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#adminId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='adminId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>216d8c00-a568-41d1-b977-32fe27c68e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>914e9d07-5015-48e2-aa0f-735414cfe9e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>adminId</value>
      <webElementGuid>d224d620-d069-4056-87fa-7b5317c8abab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>4~20자 입력</value>
      <webElementGuid>2729c8b0-5aea-4a0b-a54f-1e46bc0d937d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>57b007e1-afb1-458d-9a03-99f9e28bf339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adminId&quot;)</value>
      <webElementGuid>b6f1cb3f-3e6c-41e8-b52b-88bf77263699</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='adminId']</value>
      <webElementGuid>eb681f31-a854-43a8-a8cd-d5cecf267a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='adminForm']/div/div/input</value>
      <webElementGuid>1f58656b-8157-4bf2-968d-daccc40d58db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ff57b379-a5ef-4ff4-a3b2-ae98851d3bb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'adminId' and @placeholder = '4~20자 입력']</value>
      <webElementGuid>bd14b711-06e8-4130-8130-addf2f71e37c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
