<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LOGIN_manager_pw</name>
   <tag></tag>
   <elementGuidId>9a11b133-9b00-42a7-bb52-7037f2fa2ddd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;manager_pw&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='manager_pw']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8efe0df9-d6d7-4e64-a233-c660b1d37619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>manager_pw</value>
      <webElementGuid>ccd6e86a-f4ab-42df-aeaf-a538d221b730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d502c6f2-9dfb-451c-b044-381c7ff93aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-pw</value>
      <webElementGuid>af83f483-6221-4437-b766-6db79df49117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>2de903ec-e7f1-4c67-b12e-65d14daa92b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-check</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>5cef3f22-27d2-4a92-9b9d-e427d5b4f572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;login-02&quot;]/form[1]/div[@class=&quot;login-input&quot;]/div[@class=&quot;password-wrapper&quot;]/input[@class=&quot;login-pw&quot;]</value>
      <webElementGuid>a91a9b0c-459e-4983-b1d2-dc50ff4f6a4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='manager_pw']</value>
      <webElementGuid>1697cb6f-b7ab-4f89-833c-68c5daf624fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/form/div/div/input</value>
      <webElementGuid>154ba09c-c456-47a5-b109-403689a7132b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>436c9304-3b70-41ef-9a88-e81eff2604a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'manager_pw' and @type = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>497b0ef8-db5d-4ad4-9c12-7c6f1d82729f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
