<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>c89b45c0-a062-4f56-9c38-37fa6a624d95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='signupForm']/div[4]/div/label/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7407377c-1f64-40a8-aeac-417885e7a828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center px-4 py-3 border border-gray-300 rounded-xl text-gray-600 font-medium transition-colors hover:bg-gray-50</value>
      <webElementGuid>17349a48-3083-427b-ae4b-d27bf24c2d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>남성</value>
      <webElementGuid>25bc27db-b63b-4b0f-9ac1-094d1a1f788c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signupForm&quot;)/div[4]/div[@class=&quot;grid grid-cols-3 gap-4&quot;]/label[@class=&quot;cursor-pointer relative&quot;]/div[@class=&quot;text-center px-4 py-3 border border-gray-300 rounded-xl text-gray-600 font-medium transition-colors hover:bg-gray-50&quot;]</value>
      <webElementGuid>7773d0aa-920d-43f5-b506-48d5dae69f50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div[4]/div/label/div</value>
      <webElementGuid>932fc8e5-e009-45c0-a975-839e8647e619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::div[2]</value>
      <webElementGuid>79c23a59-11db-494a-8d1d-5200261ebede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='여성'])[1]/preceding::div[1]</value>
      <webElementGuid>9cc97690-6255-4bfc-b65e-328765340bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='선택안함'])[1]/preceding::div[2]</value>
      <webElementGuid>b89a3735-3b36-49f4-86af-613edd8f387d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='남성']/parent::*</value>
      <webElementGuid>17350a86-6ec4-41ca-adc0-533cd5cec5c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>31e546d4-47b4-4aee-aefe-1df29adb0b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '남성' or . = '남성')]</value>
      <webElementGuid>9430f073-d3a6-41a5-afba-04781c7bf84f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
