<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>c89b45c0-a062-4f56-9c38-37fa6a624d95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='signupForm']/div[4]/div/label/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2ab5f780-6e0a-4ef3-a0c4-a11210308f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center px-4 py-3 border border-gray-300 rounded-xl text-gray-600 font-medium transition-colors hover:bg-gray-50</value>
      <webElementGuid>163990d8-0448-412b-99c3-7642fe3e1cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>남성</value>
      <webElementGuid>71274e50-9137-4619-94c1-cae62b6e7a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signupForm&quot;)/div[4]/div[@class=&quot;grid grid-cols-3 gap-4&quot;]/label[@class=&quot;cursor-pointer relative&quot;]/div[@class=&quot;text-center px-4 py-3 border border-gray-300 rounded-xl text-gray-600 font-medium transition-colors hover:bg-gray-50&quot;]</value>
      <webElementGuid>d9dd9ccb-efbe-45e9-a0ca-9879c5b8e8ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div[4]/div/label/div</value>
      <webElementGuid>0937f643-b4fb-4dfc-ba78-dfacd73d0a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::div[2]</value>
      <webElementGuid>7e769f58-0405-4817-b4b1-afb042357664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='여성'])[1]/preceding::div[1]</value>
      <webElementGuid>640a5d47-81b4-4bc9-97eb-04371da89ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='선택안함'])[1]/preceding::div[2]</value>
      <webElementGuid>bc40bc34-7c49-4a56-b2df-61e83cf02504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='남성']/parent::*</value>
      <webElementGuid>a78cfaef-ab0f-4819-bab4-64e4b9c91b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>628c2929-b21b-4c38-ace2-71b703810c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '남성' or . = '남성')]</value>
      <webElementGuid>f1219be4-4a87-4281-a2c8-a438027dc370</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
