<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe___kakao__viewerFrame_1</name>
   <tag></tag>
   <elementGuidId>09ca4069-1e85-4fe7-9eb6-1b9e7cceb416</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='__kakao__viewerFrame_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__kakao__viewerFrame_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>0e6d5e3a-85ba-41eb-9793-ef1fbed191e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5b653bd6-c923-4f30-9688-1f7921cf4902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>우편번호 검색 프레임</value>
      <webElementGuid>96038e5c-7be8-4002-b1cc-a324cd70e962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__kakao__viewerFrame_1</value>
      <webElementGuid>077a46df-e0f6-4a3d-92c6-21f9c4e3699d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://postcode.map.daum.net/search?origin=file%3A%2F%2F&amp;inc=&amp;indaum=off&amp;banner=on&amp;ubl=on&amp;mode=transmit&amp;vt=layer&amp;amr=on&amp;amj=on&amp;ani=off&amp;sd=on&amp;fi=on&amp;fc=on&amp;plrg=&amp;plrgt=1.5&amp;hmb=off&amp;heb=off&amp;asea=off&amp;smh=off&amp;zo=on&amp;us=on&amp;msi=10&amp;ahs=off&amp;whas=500&amp;sm=on&amp;a51=off&amp;zn=Y&amp;fullpath=%2FC%3A%2FUsers%2Fssr0128%2FDesktop%2Fpage%2FJoin3.html</value>
      <webElementGuid>c98ca6bb-0c29-4eb2-9730-abeeec14a3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__kakao__viewerFrame_1&quot;)</value>
      <webElementGuid>499dab39-8a34-48bc-9343-a576d9431e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/join3/Page_/iframe</value>
      <webElementGuid>e1ff6df0-3635-43ed-8b00-e0cf9e800387</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='__kakao__viewerFrame_1']</value>
      <webElementGuid>0a96524b-066e-490d-a647-3d10ab5f357b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>12ad6ddb-8135-4a07-8dc3-1aac71e04e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = '우편번호 검색 프레임' and @id = '__kakao__viewerFrame_1' and @src = 'https://postcode.map.daum.net/search?origin=file%3A%2F%2F&amp;inc=&amp;indaum=off&amp;banner=on&amp;ubl=on&amp;mode=transmit&amp;vt=layer&amp;amr=on&amp;amj=on&amp;ani=off&amp;sd=on&amp;fi=on&amp;fc=on&amp;plrg=&amp;plrgt=1.5&amp;hmb=off&amp;heb=off&amp;asea=off&amp;smh=off&amp;zo=on&amp;us=on&amp;msi=10&amp;ahs=off&amp;whas=500&amp;sm=on&amp;a51=off&amp;zn=Y&amp;fullpath=%2FC%3A%2FUsers%2Fssr0128%2FDesktop%2Fpage%2FJoin3.html']</value>
      <webElementGuid>3712eb35-8679-4db5-8885-722f71d31e75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
