<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__sample4_detailAddress</name>
   <tag></tag>
   <elementGuidId>baf87109-3dd2-4468-acfe-21246a6129a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sample4_detailAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sample4_detailAddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b997a1ac-4251-4114-be24-90c9a4d14218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>895d69cf-38e9-4548-8d31-c207cd5d9626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sample4_detailAddress</value>
      <webElementGuid>26290d94-886c-4b86-97f5-90acd3128dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>상세주소를 입력해주세요</value>
      <webElementGuid>a354c760-db7d-42ce-ba9e-f8f6c4ae1204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-transition w-full px-4 py-3 rounded-xl border border-gray-300 focus:ring-2 focus:ring-primary focus:border-primary outline-none</value>
      <webElementGuid>16fa744f-7c2c-499b-9506-178ff0b670ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sample4_detailAddress&quot;)</value>
      <webElementGuid>4eed3fc8-9f85-4dc2-ab52-ae553a944bde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sample4_detailAddress']</value>
      <webElementGuid>d2fc5a1e-e7dc-42af-83b8-c2a1b4e956f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div[6]/input[3]</value>
      <webElementGuid>a7ca2ccb-ced5-4a14-9660-a216345471b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>ddfcc52b-339a-4bf0-aadd-4f31c99c18dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'sample4_detailAddress' and @placeholder = '상세주소를 입력해주세요']</value>
      <webElementGuid>100a1b24-52ec-45a8-bc26-da54ca3cdbc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
