<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__passwordConfirm</name>
   <tag></tag>
   <elementGuidId>954e1ccd-f4e0-4d44-9c63-10c6f621c919</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#passwordConfirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='passwordConfirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2abf313b-cde3-4d80-94b0-330f4d6fdade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>329a2e15-18ee-49cd-aadf-a73330399aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passwordConfirm</value>
      <webElementGuid>c78346b8-5664-4806-bb47-f04bf9a3b0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>다시 입력</value>
      <webElementGuid>514d8992-a12f-4d57-965a-e1ff6ba961ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-base</value>
      <webElementGuid>17776f10-43e4-4959-acad-6eb53b70c582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passwordConfirm&quot;)</value>
      <webElementGuid>c61f72ef-c2ff-43e8-bc25-363ba1cab18e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='passwordConfirm']</value>
      <webElementGuid>0d1747a2-6187-4b9e-b798-e8a973724869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div[3]/div[2]/input</value>
      <webElementGuid>76bdde91-9e5c-4eaf-ba56-b22792e76b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>6c8571cf-fdd4-48fe-a47d-642a8ab72870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'passwordConfirm' and @placeholder = '다시 입력']</value>
      <webElementGuid>9af0f73d-a80b-48e1-a0da-bab32137aa2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div[2]/div[2]/input</value>
      <webElementGuid>18080e7a-cb0f-4b0b-865a-93f3a34a2861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'passwordConfirm' and @placeholder = '비밀번호 재입력']</value>
      <webElementGuid>c5c2c315-9303-4d97-ba54-387821c57328</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
