<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__userName</name>
   <tag></tag>
   <elementGuidId>d6722292-4b19-4578-b69d-e3ee6c3efcf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#userName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='userName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aae9bd80-cdf7-46a4-a8fe-70cd39282e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e108086a-0289-4bca-b1ce-81a9cda04761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userName</value>
      <webElementGuid>54266383-e7e5-45c8-a42a-e366f84fd55b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>이름을 선택해주세요</value>
      <webElementGuid>edfd76a9-997e-4b07-8c3f-109494980fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-base pr-12 cursor-pointer group-hover:border-primary/50</value>
      <webElementGuid>cd893f6d-5e6e-47dd-811e-e75dc8069b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userName&quot;)</value>
      <webElementGuid>aedd2ec3-4887-4271-851f-07fb9735a9c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='userName']</value>
      <webElementGuid>3e4ed71f-abc8-4879-bd1e-0e7faa1b564e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div/div/input</value>
      <webElementGuid>705d4d59-8cda-41f0-af6d-b3c3af396183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8fccb45f-c678-48e6-a998-df8cf8998705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'userName' and @placeholder = '이름을 선택해주세요']</value>
      <webElementGuid>6d14a407-9032-45da-be8f-349a464307c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div[3]/input</value>
      <webElementGuid>b5bbbbf1-bded-411b-84f9-eb52e8fbba03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>7859dcc2-07db-4a43-ac93-06b7692cda8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'userName' and @placeholder = '성함을 입력하세요']</value>
      <webElementGuid>3773838c-9069-4aab-a31b-41877b9104a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
