<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_, )  166,  ,  532_region_name</name>
   <tag></tag>
   <elementGuidId>47988de5-0dac-4f7e-aba6-91f693d251fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='region_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#region_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>041bc4a8-d74e-4e8f-93cd-fb81ddb83109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>de3d91c9-616e-41c7-a9fd-7b53b4727906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>region_name</value>
      <webElementGuid>9f5dc039-438b-44c5-881b-262fab743977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>주소 검색</value>
      <webElementGuid>e38aea14-f786-43f7-9cda-86975d4a9156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tf_keyword</value>
      <webElementGuid>a86d6b49-8a3f-4c5d-8891-384f6a2b57c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>region_name</value>
      <webElementGuid>f4e1d632-a385-48c4-b929-05ef740d44f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4d707d9f-3d93-4bed-8af8-0f8eac2b1e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clearable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d6eaac64-a975-42bd-b857-5ade39a3bfcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;region_name&quot;)</value>
      <webElementGuid>151cda82-2b5e-45c2-8549-18f24ddf9f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/join3/Page_/iframe___kakao__viewerFrame_1</value>
      <webElementGuid>f09a4302-90a6-4395-ae58-0d7ed419d198</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='region_name']</value>
      <webElementGuid>1587e05d-227b-40ec-9e2b-8e71db747222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/fieldset/div/div/input</value>
      <webElementGuid>38daca91-341d-4c00-ac2d-3ed0799c6675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>951a1d8e-3556-41e0-83bf-a2103c60731f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'region_name' and @title = '주소 검색' and @name = 'region_name']</value>
      <webElementGuid>206bebe7-c1c3-40bd-b3eb-62bbf1bbcf0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
