<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(        286)_sample4_detailAddress</name>
   <tag></tag>
   <elementGuidId>94c8a005-a60c-42cd-8504-df1c165179e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sample4_detailAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sample4_detailAddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0d6170b-7553-424a-9bc8-25f46b072bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e789c4f1-cf04-4a01-8327-c716a9e7fd84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sample4_detailAddress</value>
      <webElementGuid>0c621f49-b27b-41f6-a098-3f84cc95231b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>상세주소를 입력해주세요</value>
      <webElementGuid>22c13370-a0cc-45b9-8959-1743dbe8b304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-transition w-full px-4 py-3 rounded-xl border border-gray-300 focus:ring-2 focus:ring-primary focus:border-primary outline-none</value>
      <webElementGuid>0eb4fc4f-db14-46b8-b6d0-071b3ffe0c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sample4_detailAddress&quot;)</value>
      <webElementGuid>0beb8d78-9307-409c-8eb0-cd9a561f116c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sample4_detailAddress']</value>
      <webElementGuid>d34366ad-82b5-4a95-9de7-26ae7d1f2f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div[6]/input[3]</value>
      <webElementGuid>48f62a25-ea92-4017-85f3-976fdec08ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>11327920-0051-457e-9c4b-bf2b49336e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'sample4_detailAddress' and @placeholder = '상세주소를 입력해주세요']</value>
      <webElementGuid>e89b3542-09f5-4ef1-9094-fa71f970fa6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
