<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__sample4_jibunAddress</name>
   <tag></tag>
   <elementGuidId>f44c551d-c35e-427a-909b-fe48aa74387c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sample4_jibunAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sample4_jibunAddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19c97b3b-d471-49d7-af0f-ea17ec693f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e8cb920-1a96-4243-85e1-9dc5a2b922a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sample4_jibunAddress</value>
      <webElementGuid>9573b789-dfe2-40fd-bd0b-2498eed722ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>지번주소</value>
      <webElementGuid>a8badbe6-18c0-4f01-b8c7-f9d0b94142f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-transition w-full px-4 py-3 rounded-xl border border-gray-300 bg-gray-50 outline-none</value>
      <webElementGuid>da637316-8caf-4d7d-bbd2-2e371d33c127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sample4_jibunAddress&quot;)</value>
      <webElementGuid>a5736fda-93e4-4f13-9de8-06d66102b3ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sample4_jibunAddress']</value>
      <webElementGuid>c779fa46-8309-4fde-9a27-c1c831f86d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div[6]/input[2]</value>
      <webElementGuid>a82bff19-181c-4272-a69a-49c5af55c8d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>f58e6b7d-8e90-4250-adb6-394e4f0501ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'sample4_jibunAddress' and @placeholder = '지번주소']</value>
      <webElementGuid>e25cea44-30a3-437a-ac64-ae5370264b61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
