<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__sample4_extraAddress</name>
   <tag></tag>
   <elementGuidId>cd8ee56d-fe64-470f-aaa3-c85eebdd4709</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sample4_extraAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sample4_extraAddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71f92e62-28cf-4944-bdc7-b6fd2959221c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d1681296-a07a-42d2-a269-edaae1dad68f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sample4_extraAddress</value>
      <webElementGuid>f5c06a3f-4f3e-456e-89ef-2d0b2cfd6ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>참고항목</value>
      <webElementGuid>1759fd6e-786b-4af8-8e6a-5fde7bbefa47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-transition w-full px-4 py-3 rounded-xl border border-gray-300 bg-gray-50 outline-none</value>
      <webElementGuid>a900c8d6-87a7-488d-89ca-191b9aa7253a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sample4_extraAddress&quot;)</value>
      <webElementGuid>1df357b3-48b0-4a9b-8ed9-16329a7f73ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sample4_extraAddress']</value>
      <webElementGuid>277a428a-2867-44b0-8d1a-866d560f8fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div[6]/input[4]</value>
      <webElementGuid>fd110c94-a3e2-479d-b97d-061090b89a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>ba97cc64-edd0-43b8-b0ae-0719d65e9ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'sample4_extraAddress' and @placeholder = '참고항목']</value>
      <webElementGuid>eec3c868-895f-4de0-b324-bc33db3c3985</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
