<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SKT                        KT       _9a0272</name>
   <tag></tag>
   <elementGuidId>f4be781a-5927-4336-9f15-cbffbe48664d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.input-transition.w-full.px-4.py-3.rounded-xl.border.border-gray-300.outline-none.bg-white</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='signupForm']/div[6]/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>40577b9e-3544-4173-930d-22c328d9c003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>telecom</value>
      <webElementGuid>1a7a56f4-992b-48ea-9dee-a7642a23acc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-transition w-full px-4 py-3 rounded-xl border border-gray-300 outline-none bg-white</value>
      <webElementGuid>576127ed-a1d0-4beb-8856-fd49afb1b1d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        선택
                        SKT
                        KT
                        LGU+
                    </value>
      <webElementGuid>00f08968-6900-4b92-9601-b2ac8438461c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signupForm&quot;)/div[@class=&quot;grid grid-cols-1 md:grid-cols-3 gap-4&quot;]/div[1]/select[@class=&quot;input-transition w-full px-4 py-3 rounded-xl border border-gray-300 outline-none bg-white&quot;]</value>
      <webElementGuid>f4a52a0c-a549-4121-866a-b95b17485da4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div[6]/div/select</value>
      <webElementGuid>46c147cf-a557-4fe6-bac3-2fbb719b7460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='통신사'])[1]/following::select[1]</value>
      <webElementGuid>1a2e83ad-4f83-4863-939a-7e9431dbfb50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='테스트용이미지.png'])[1]/following::select[1]</value>
      <webElementGuid>fbdef9c5-bbeb-445d-9c7a-27dc7a940f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='이메일'])[1]/preceding::select[1]</value>
      <webElementGuid>a0dcecd0-2486-4bbf-ad29-dae8f84c371e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='직업'])[1]/preceding::select[2]</value>
      <webElementGuid>baa0c413-7d8b-48f2-aac0-8330bf894e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>f23a1296-4df3-46f4-a439-1214c304d71e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = '
                        선택
                        SKT
                        KT
                        LGU+
                    ' or . = '
                        선택
                        SKT
                        KT
                        LGU+
                    ')]</value>
      <webElementGuid>9a3242fc-6925-4ae8-ad58-23279ae9bb81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='telecom']</value>
      <webElementGuid>49cff504-f06c-44de-8668-bfb362bce922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div[7]/div/select</value>
      <webElementGuid>e8ebf1a6-f4d2-45b2-a970-c7fb1384a2df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(예상 지번 주소 : 경기 가평군 가평읍 대곡리 286)'])[1]/following::select[1]</value>
      <webElementGuid>1bc931d8-8c27-4006-aaad-5710bb428ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='이메일 도메인'])[1]/preceding::select[1]</value>
      <webElementGuid>e8ecb0df-f0e7-4660-a9b0-5881cd7c3ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'telecom' and (text() = '
                        선택
                        SKT
                        KT
                        LGU+
                        알뜰폰
                    ' or . = '
                        선택
                        SKT
                        KT
                        LGU+
                        알뜰폰
                    ')]</value>
      <webElementGuid>3ec2c935-f031-4e79-9125-21d452c1b1d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='주소 검색'])[1]/following::select[1]</value>
      <webElementGuid>e21431e4-a1ab-4718-84af-a2657130fcec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
