<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_</name>
   <tag></tag>
   <elementGuidId>eee5c47e-2426-4ec4-9e91-d066546d2eba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(3) > select.input-transition.w-full.px-4.py-3.rounded-xl.border.border-gray-300.outline-none.bg-white</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='signupForm']/div[6]/div[3]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>263f4614-d970-4cb9-b017-b13dbddf362e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>job</value>
      <webElementGuid>fc1ee58e-dc16-45d2-b784-f71f1e10fcaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-transition w-full px-4 py-3 rounded-xl border border-gray-300 outline-none bg-white</value>
      <webElementGuid>5d8875ab-004e-4b7d-a91f-ea7986cff7e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        선택
                        직장인
                        학생
                    </value>
      <webElementGuid>6e108be9-2dd7-49a3-ae89-588dcaff2201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signupForm&quot;)/div[@class=&quot;grid grid-cols-1 md:grid-cols-3 gap-4&quot;]/div[3]/select[@class=&quot;input-transition w-full px-4 py-3 rounded-xl border border-gray-300 outline-none bg-white&quot;]</value>
      <webElementGuid>c4c1d906-0aac-4cae-84c9-d3fce9b90b33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div[6]/div[3]/select</value>
      <webElementGuid>a5ba2149-0e63-4163-a47f-c405e5b08c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='직업'])[1]/following::select[1]</value>
      <webElementGuid>be25719f-19d2-42a2-87c9-c125ec6a267b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='이메일'])[1]/following::select[2]</value>
      <webElementGuid>2d95cf93-93e5-46d8-a904-8a1821bae371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='전체 약관 동의'])[1]/preceding::select[1]</value>
      <webElementGuid>1267ab2b-c8ac-4bbb-8794-93b5f102bb8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[필수] 서비스 이용약관 동의'])[1]/preceding::select[1]</value>
      <webElementGuid>43d76cf4-3bf1-4efe-ad74-a5a030db2c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>368add8a-1f77-463a-be11-d8414ed2a1bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = '
                        선택
                        직장인
                        학생
                    ' or . = '
                        선택
                        직장인
                        학생
                    ')]</value>
      <webElementGuid>00130f96-1708-4e69-b40f-00fd96f0e912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='job']</value>
      <webElementGuid>026adcc6-e94d-4fbb-9bd6-5d96b5043d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div[7]/div[3]/select</value>
      <webElementGuid>e5b430f8-8cf6-421d-8d6b-c7b011753e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='이메일 도메인'])[1]/following::select[2]</value>
      <webElementGuid>0fabe098-2cdb-4a19-973c-7b951df74398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='전체 약관에 동의합니다.'])[1]/preceding::select[1]</value>
      <webElementGuid>066d37dc-6644-41d1-bbbd-42cad41a032e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'job' and (text() = '
                        선택
                        학생
                        직장인
                        프리랜서
                    ' or . = '
                        선택
                        학생
                        직장인
                        프리랜서
                    ')]</value>
      <webElementGuid>e6876501-af68-4a43-bed3-9d2ae7f4baae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
