<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SKT                        KT       _9a0272</name>
   <tag></tag>
   <elementGuidId>f4be781a-5927-4336-9f15-cbffbe48664d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='telecom']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#telecom</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4804e1cf-3d06-41e2-9f29-8003843e96d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>telecom</value>
      <webElementGuid>1a7a56f4-992b-48ea-9dee-a7642a23acc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-transition w-full px-4 py-3 rounded-xl border border-gray-300 focus:ring-2 focus:ring-primary outline-none bg-white</value>
      <webElementGuid>b05fa7b3-c123-46be-b493-98c0ef2d6ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        선택
                        SKT
                        KT
                        LGU+
                        알뜰폰
                    </value>
      <webElementGuid>d206c2b9-a0be-4464-b948-8e513d90e359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;telecom&quot;)</value>
      <webElementGuid>a6d72e80-92ae-4277-ba5d-23d57d21e9e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='telecom']</value>
      <webElementGuid>49cff504-f06c-44de-8668-bfb362bce922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div[7]/div/select</value>
      <webElementGuid>e8ebf1a6-f4d2-45b2-a970-c7fb1384a2df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='통신사'])[1]/following::select[1]</value>
      <webElementGuid>b51b06d4-d874-44b2-a259-5aab6d6e0895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(예상 지번 주소 : 경기 가평군 가평읍 대곡리 286)'])[1]/following::select[1]</value>
      <webElementGuid>1bc931d8-8c27-4006-aaad-5710bb428ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='이메일 도메인'])[1]/preceding::select[1]</value>
      <webElementGuid>e8ecb0df-f0e7-4660-a9b0-5881cd7c3ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='직업'])[1]/preceding::select[2]</value>
      <webElementGuid>99d085c2-84e6-4011-babc-2822807d6833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>953cfa10-9353-4a40-8b1b-2b92e6f358b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'telecom' and (text() = '
                        선택
                        SKT
                        KT
                        LGU+
                        알뜰폰
                    ' or . = '
                        선택
                        SKT
                        KT
                        LGU+
                        알뜰폰
                    ')]</value>
      <webElementGuid>3ec2c935-f031-4e79-9125-21d452c1b1d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='주소 검색'])[1]/following::select[1]</value>
      <webElementGuid>e21431e4-a1ab-4718-84af-a2657130fcec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
