<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_naver.com                        gma_f566ea</name>
   <tag></tag>
   <elementGuidId>5300527c-cadf-46ab-aedc-2b3c1b3186bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='emailDomain']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#emailDomain</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8eb3eedc-5e6d-42b6-95b4-e5cb594fc03a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailDomain</value>
      <webElementGuid>2bf6a109-c308-46e0-9470-0f9ba7e114cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-transition w-full px-4 py-3 rounded-xl border border-gray-300 focus:ring-2 focus:ring-primary outline-none bg-white</value>
      <webElementGuid>0f403349-6acc-470b-a3b3-8a2fb3896f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        선택
                        naver.com
                        gmail.com
                        daum.net
                    </value>
      <webElementGuid>0e3f863b-551a-402c-ac4c-487fcd45695b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailDomain&quot;)</value>
      <webElementGuid>fc08a2a7-b65c-4f88-953b-ec663097268a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='emailDomain']</value>
      <webElementGuid>4c924e34-0587-4cec-ae29-43b4c1ccd1e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div[7]/div[2]/select</value>
      <webElementGuid>2843c942-026b-432d-92a7-e5e91dda913b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='이메일 도메인'])[1]/following::select[1]</value>
      <webElementGuid>75688724-99d0-422e-adbd-5ce54947c8e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='통신사'])[1]/following::select[2]</value>
      <webElementGuid>3814e2b4-a918-4b0f-984a-25f657a3b110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='직업'])[1]/preceding::select[1]</value>
      <webElementGuid>da2cb3e1-ee5e-460e-aa9e-9a19e7629eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='전체 약관에 동의합니다.'])[1]/preceding::select[2]</value>
      <webElementGuid>760d839b-69a3-487b-9c28-513c28cae303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>1d33b24e-b938-4072-80c4-a27a71ff50b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'emailDomain' and (text() = '
                        선택
                        naver.com
                        gmail.com
                        daum.net
                    ' or . = '
                        선택
                        naver.com
                        gmail.com
                        daum.net
                    ')]</value>
      <webElementGuid>dc8258ae-16d0-4abd-999f-de69083e62a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
