<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>a6b866a4-f98f-41c4-ab0c-2a32db37b377</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='signupForm']/div[8]/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.font-bold.text-gray-800</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0060cc8b-fc75-4282-849c-7d8f9af708f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-bold text-gray-800</value>
      <webElementGuid>450d9e9f-bb53-4a07-bf5d-c48d5bbe450f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>전체 약관에 동의합니다.</value>
      <webElementGuid>8310f895-e5e0-4174-9ad8-0849bf8e2b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signupForm&quot;)/div[@class=&quot;bg-gray-50 p-5 rounded-2xl border border-gray-200&quot;]/label[@class=&quot;flex items-center space-x-3 mb-4 border-b pb-4 cursor-pointer&quot;]/span[@class=&quot;font-bold text-gray-800&quot;]</value>
      <webElementGuid>757ba0f2-4794-4edd-ba5e-39a97b91cb70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signupForm']/div[8]/label/span</value>
      <webElementGuid>3e3f6ba0-0d8a-4f18-9146-d4b1ac3bae1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='직업'])[1]/following::span[1]</value>
      <webElementGuid>8e7dd833-88e4-4e8a-b863-1b16792772b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='이메일 도메인'])[1]/following::span[1]</value>
      <webElementGuid>f02302fc-11e9-45fa-8970-7a381eb573f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[필수] 서비스 이용약관 동의'])[1]/preceding::span[1]</value>
      <webElementGuid>c17e19f7-585d-4859-8bb6-9052fd2ec613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[필수] 개인정보 수집 및 이용 동의'])[1]/preceding::span[2]</value>
      <webElementGuid>19801eda-dcd1-42db-a236-1de5d23bd571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='전체 약관에 동의합니다.']/parent::*</value>
      <webElementGuid>15307f60-15b7-4bb5-9a0e-fdd3fba0c4ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/label/span</value>
      <webElementGuid>3db1aab7-51d6-47b1-915e-b8ca67d01531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '전체 약관에 동의합니다.' or . = '전체 약관에 동의합니다.')]</value>
      <webElementGuid>2ab9bc12-7680-417e-997d-c84df82c74df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
