<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__userId</name>
   <tag></tag>
   <elementGuidId>ffe68a65-9cc6-4bbe-a0f5-20b50551a3bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='userId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#userId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57a524b0-2238-4d05-9ad0-1d5fb91ca201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9af63ea-e205-420d-ab35-330a2312117c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userId</value>
      <webElementGuid>8920da18-2772-4aa1-bb3a-097710040b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>4~12자 영문/숫자</value>
      <webElementGuid>5ec36331-64ca-4873-9b12-5ecdbd44906a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userId&quot;)</value>
      <webElementGuid>ea9b4a93-dc98-4046-8410-24132e77643e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='userId']</value>
      <webElementGuid>b48c9670-ca5d-4823-9b83-d886007b2007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='joinForm']/div[2]/div/div[2]/div/input</value>
      <webElementGuid>d6e85019-43c6-4cd2-930f-f034f64921ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>1a40e5ba-6570-4a1f-856e-7c953b4ca33e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'userId' and @placeholder = '4~12자 영문/숫자']</value>
      <webElementGuid>1cebf1a6-03f2-4e03-bc4c-4d4ef1122d84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
