<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_</name>
   <tag></tag>
   <elementGuidId>e64ced24-5732-4a80-86f5-b5d36853db8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='joinForm']/div[4]/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.check-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>391f5906-07ad-4051-8153-0f5cee835c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>check-item</value>
      <webElementGuid>78ecc66b-182d-4aaa-a932-dd89966224cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> [필수] 이용약관 동의</value>
      <webElementGuid>81ebf7e0-dbf9-4a1b-a6f6-fc92be9e9c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;joinForm&quot;)/div[@class=&quot;form-section&quot;]/div[@class=&quot;check-list&quot;]/label[@class=&quot;check-item&quot;]</value>
      <webElementGuid>20275b4b-1d8f-4e97-8ef8-828f638368c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='joinForm']/div[4]/div/label</value>
      <webElementGuid>e25c8929-713f-48a4-9453-c53e9c7e5c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='주소 찾기'])[1]/following::label[1]</value>
      <webElementGuid>3d2c79ee-f851-4644-8cc0-49ab25920753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='비밀번호 확인'])[1]/following::label[1]</value>
      <webElementGuid>08725057-329b-4e69-8fff-d38fd46c9451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[필수] 개인정보 처리방침 동의'])[1]/preceding::label[1]</value>
      <webElementGuid>e36181f3-9484-4707-b35a-7d2f5456f925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[선택] 이벤트 알림 수신'])[1]/preceding::label[2]</value>
      <webElementGuid>e7d9554b-3f3b-4753-a0d1-1f71a25dae26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='[필수] 이용약관 동의']/parent::*</value>
      <webElementGuid>104d8807-f5ec-41b4-b0e8-fcb0d87256b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/label</value>
      <webElementGuid>0f9dfe57-c5e6-46f9-8bba-b3d1686194a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' [필수] 이용약관 동의' or . = ' [필수] 이용약관 동의')]</value>
      <webElementGuid>207c6504-b3b6-4fc8-b8e8-f4fb65f0a3c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='joinForm']/div[4]/div/label[2]</value>
      <webElementGuid>9b92dfe7-ee3b-498f-8950-1e629f92939e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[필수] 이용약관 동의'])[1]/following::label[1]</value>
      <webElementGuid>6dd7808d-000f-4d9f-bbd4-ce974ed1591b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='주소 찾기'])[1]/following::label[2]</value>
      <webElementGuid>1aab6158-8fb6-446f-b729-cbfc97d98add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[선택] 이벤트 알림 수신'])[1]/preceding::label[1]</value>
      <webElementGuid>f8d5d27d-c2e0-4fca-bf42-31d0c7b8020c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='가입하기'])[1]/preceding::label[2]</value>
      <webElementGuid>2e40d303-43d3-4699-8191-2623d315302e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='[필수] 개인정보 처리방침 동의']/parent::*</value>
      <webElementGuid>7e7580b8-595c-4a1c-8d45-b8c860eccd0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/label[2]</value>
      <webElementGuid>df01df5c-a09a-40e1-8230-23e7480ed825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' [필수] 개인정보 처리방침 동의' or . = ' [필수] 개인정보 처리방침 동의')]</value>
      <webElementGuid>ebbfd99c-95e7-429c-8fdb-0744f7116d13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
