<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label__1</name>
   <tag></tag>
   <elementGuidId>e98dc3c5-7b4c-4887-8afd-8af54f5048ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='joinForm']/div[4]/div/label[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7923e220-7e2f-4895-a55f-f547b80da84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>check-item</value>
      <webElementGuid>3747c61a-d446-47e8-8ef7-1f95e2a0e88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> [필수] 개인정보 처리방침 동의</value>
      <webElementGuid>f78a12bc-9b1b-4da9-b0c8-9fc512f9abbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;joinForm&quot;)/div[@class=&quot;form-section&quot;]/div[@class=&quot;check-list&quot;]/label[@class=&quot;check-item&quot;]</value>
      <webElementGuid>218242fb-4530-4aad-bab7-e00609e10ad5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='joinForm']/div[4]/div/label[2]</value>
      <webElementGuid>05af5396-3a87-46eb-95ce-25262517c0ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[필수] 이용약관 동의'])[1]/following::label[1]</value>
      <webElementGuid>7f430a39-4615-4942-8c5c-f3ac656fbfd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='주소 찾기'])[1]/following::label[2]</value>
      <webElementGuid>378ed8fb-f0b2-4565-8f55-6ead261b5744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[선택] 이벤트 알림 수신'])[1]/preceding::label[1]</value>
      <webElementGuid>5b2fdb83-8c9e-4add-a28e-6eb2046f7c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='가입하기'])[1]/preceding::label[2]</value>
      <webElementGuid>b537f2ba-1855-4119-98a5-1f2866a9f606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='[필수] 개인정보 처리방침 동의']/parent::*</value>
      <webElementGuid>9abfbc64-8f1a-4802-a83e-cd5ad79ae37f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/label[2]</value>
      <webElementGuid>639bca01-67f0-456c-a38d-be6c7bdaab25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' [필수] 개인정보 처리방침 동의' or . = ' [필수] 개인정보 처리방침 동의')]</value>
      <webElementGuid>bbb3d33b-fc82-4502-bce9-e487269a1e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='joinForm']/div[4]/div/label[3]</value>
      <webElementGuid>012e1357-9b1a-447f-a4ae-2d54781d9eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[필수] 개인정보 처리방침 동의'])[1]/following::label[1]</value>
      <webElementGuid>0190ff39-c614-4415-a136-d94c8a2da7f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[필수] 이용약관 동의'])[1]/following::label[2]</value>
      <webElementGuid>5f39215c-13ed-45ee-8e9f-e4596aeb2312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='가입하기'])[1]/preceding::label[1]</value>
      <webElementGuid>44ccbd47-fb4a-4da3-94af-9d5bd9cb321a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='[선택] 이벤트 알림 수신']/parent::*</value>
      <webElementGuid>1357b669-6bc6-4229-bc8c-daf34c521d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[3]</value>
      <webElementGuid>6e8aa2d6-6baf-4ffb-801c-eaea8e50b39f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' [선택] 이벤트 알림 수신' or . = ' [선택] 이벤트 알림 수신')]</value>
      <webElementGuid>5de9704b-4799-4694-8216-eabe8d2403b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
