<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_ID</name>
   <tag></tag>
   <elementGuidId>03d1b41e-bf44-4db3-b207-bf36586de341</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='joinForm']/div/div/label[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3aca31e7-b847-49f7-9d5b-3e9954d822f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-item</value>
      <webElementGuid>131925da-16bd-4fdb-b35c-29fde0fc3579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 관리자 ID</value>
      <webElementGuid>2bfec489-0560-4472-9e06-fc116dbea70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;joinForm&quot;)/div[@class=&quot;form-section&quot;]/div[@class=&quot;flex-group&quot;]/label[@class=&quot;radio-item&quot;]</value>
      <webElementGuid>3de2e45c-7ca7-4ff8-867f-02cac9aaffed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='joinForm']/div/div/label[2]</value>
      <webElementGuid>3673d7e5-5d8e-4431-8d92-ed122ed3670c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='사용자 ID'])[1]/following::label[1]</value>
      <webElementGuid>766ba184-77f3-4f0e-a9da-3c5db8c4d5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='회원가입'])[1]/following::label[2]</value>
      <webElementGuid>91db9a3c-b5c9-4e5b-a33e-b23ccfd870fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='이름'])[1]/preceding::label[1]</value>
      <webElementGuid>bba36a14-85a5-4306-b7a1-adad9c46e96b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='아이디'])[1]/preceding::label[2]</value>
      <webElementGuid>f5777700-c301-48bd-98b2-cf45d7deadbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='관리자 ID']/parent::*</value>
      <webElementGuid>12f91a79-937b-4cf0-b203-1927561a5a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>4e47c5f8-ff46-4868-be5a-0f462bd53494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' 관리자 ID' or . = ' 관리자 ID')]</value>
      <webElementGuid>7363da82-326f-4d48-b213-10d17becee82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
