<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__operId</name>
   <tag></tag>
   <elementGuidId>db499850-76fb-4294-892b-974a5e2de5c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='operId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#operId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>081ca676-297c-4ba5-ba4c-6130ddd31c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>516d7cf8-502f-43c5-969f-02636c84f549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>operId</value>
      <webElementGuid>0ac81dcd-6319-440f-8fb0-ac7fccd59049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>operId</value>
      <webElementGuid>3d31b7a6-b208-4644-a487-986bbd1d14f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input input_id</value>
      <webElementGuid>f207578b-c85c-412b-b8aa-ee9c792c6fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>아이디를 입력하세요</value>
      <webElementGuid>fedbb9c9-dd99-410c-99d5-64b41492983e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;operId&quot;)</value>
      <webElementGuid>aa9ad715-a70d-436f-b968-b40c1faae4f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='operId']</value>
      <webElementGuid>7d23be3b-1c67-4f74-970b-3e8bb5a93f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='actionForm']/div[2]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>7179ffe6-4a65-4fa3-a7ed-05f90eecfa3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>5a003b22-3282-4766-ae21-402adad6dc42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'operId' and @name = 'operId' and @placeholder = '아이디를 입력하세요']</value>
      <webElementGuid>0ab5ed34-07ae-4cef-a421-76b3ffa27f5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
