<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__pNum</name>
   <tag></tag>
   <elementGuidId>b559ae62-508f-4167-ad9c-742140f5c6c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pNum']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pNum</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9852d4e6-b8d4-450a-913f-6c5db37c15e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7d2fb9a7-eab7-4de3-94e3-b97397394838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pNum</value>
      <webElementGuid>cab59f38-87ec-4c10-a331-85df504c1ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input input_pw</value>
      <webElementGuid>4577342c-c5f6-45a4-96d0-528236630507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>비밀번호를 입력하세요</value>
      <webElementGuid>bf49ddc1-911d-455a-b6eb-3cb2d75c8e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pNum&quot;)</value>
      <webElementGuid>5bd3feeb-1b61-412b-b999-b47ff89e9523</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pNum']</value>
      <webElementGuid>3b2eede9-4532-4180-b3b8-be621e6b9d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='actionForm']/div[2]/div[2]/div/div[3]/div/input</value>
      <webElementGuid>e34257ec-5295-484e-b05d-3e98e694e09f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>8855a9a8-6c8a-4317-a2e9-c2291fda799e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'pNum' and @placeholder = '비밀번호를 입력하세요']</value>
      <webElementGuid>9da25456-b085-4b9e-bfac-25578bff1d6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
